:lang: fr
:toc:
:toclevels: 3
:icons: font
:source-highlighter: rouge
:sectlinks:

= Langages, IA et propagande : La guerre des récits a commencé

Thème : tribues et langages

Question du bullshit. 

Ex: Pub Apple de 1984.
2 niveaux de langage :

* Imaginaire fasciste et totalitaire
* Mythologique : nouvelle chaîne de langage

L'imaginaire -> langage -> Intensions mercantiles

Umberto Eco -> Démêler le vrai du faux

Utiliser les symboles pour faire passer un message.

Comment l'utilisation des signes pour faire passer un message sans trop se soucier du vrai/faux.

== Unwelt

Unwelt -> Rapport qu'un individu entretient avec son environnement.
Par exemple, pour le poisson rouge, son unwelt c'est l'eau.

A quel point on a confiance.

Pour nous, le langage et maintenant la technologie sont des unwelts.

Bernard Stiegler -> La technologie modifie le réel. 

"Faits alternatifs"

== Fake news

Les fake news, c'est toujours les autres, jamais nous. 

Confrontation réel vécu aux discours.
-> Le bullshit
-> On remarque qu'il n'y a pas une couleur politique particulière associée aux fake news

== Comment est-ce qu'on en est arrivé là ?

. *Niveau 1* -> Le meilleur des mondes. Héritier des lumières, le signe provient du savoir. Améliore nos chemins vers l'amélioration.
Signe de l'ordre du symbole.
-> Le signe a encore un lien avec le réel
. *Niveau 2* -> Le signe connaît une perversion. L'info arrive, se succède, se remplace.
Vérité tronquée. On présente une partie de la vérité. Symbole qui réécrit -> diabole qui sépare. 
On sait faire le distingo du vrai du faux.
quelque chose de l'ordre du factice.
. *Niveau 3* -> Le signe est présent mais plus de lien avec le réel.
Le narratif n'a plus de référence au réel.
Signes qui se parlent à eux mêmes. 
Registre de l'obole, suxexposition. Désenchantement du monde.
Le réel a disparu, on n'utilise plus le réel. 
On est dans une simulation. 
. *Niveau 4* -> Le réel n'existe plus, il est obsolète. Hyper réel. On atteint ce stade là.
La matrice -> pourquoi en sortir si elle est si bien ?
Fort probable que bientôt nos identités factices seront nos identités réelles qui nous permettraient de faire des choses dans le réel. 
cf. Jean Bodriard. Il détestait le film Matrix. C'est le film que la matrice crérait pour empêcher toute alternative. 

== Conclusion

Rapport Langage/IA/Propagande

Qui fait le récit ?
-> C'est ce qui forge le réel
-> C'est celui qui code