DELETE http://localhost:8080/events/1/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzc3NDc2ODQzLCJ1c2VySWQiOjJ9.vOq7n7H9oclOyZFUt-8T7TkoF1sXI51THFnzVkhPGMA
